
name: deploy-dev
on:
  [push]

jobs:
  upload-lambda-package:
    
    runs-on: ubuntu-latest
    steps:
      - name: Package Lambda and Requirements
        run: |
          echo "${{ github.event_name }}"