name: Deploy Lambda Dev

on: [push, workflow_dispatch]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  upload-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Package Lambda and Requirements
        run: |
          pip install awscli
          aws s3 sync --delete ./target/lambda/rust-serverless-backend s3://rust-serverless-backend-lambda/${{ github.event.repository.name }}/
      
  terraform:
    needs: upload-lambda
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: |
          cd deploy
          terraform init
      - name: Terraform Plan
        id: plan
        run: |
          cd deploy
          terraform plan
      - name: Terraform Apply
        id: apply
        run: |
          cd deploy
          terraform apply -auto-approve