name: Deploy Lambda Dev

on: [push, workflow_dispatch]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  build-lambda-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Package Lambda and Requirements
        run: |
          pip install awscli
          aws s3 sync --delete ./target/lambda/rust-serverless-backend s3://rust-serverless-backend-lambdas/${{ github.event.repository.name }}/
